version: "3.8"

services:
  postgresdb:
    image: postgres
    container_name: tele-chatgpt-service-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root123
      - POSTGRES_DB=tele_chatgpt_service_db
    ports:
      - "5434:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    depends_on:
      - postgresdb
    restart: on-failure
    build: app/tele-chatgpt-service-api

    ports:
      - "8088:8080"
      - "5005:5005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/tele_chatgpt_service_db?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root123
      - SPRING_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

  frontend:
    depends_on:
      - backend
    restart: on-failure
    build: app/tele-chatgpt-service-ui
    ports:
      - "4200:4200"

volumes:
  postgres_data: